[build]
  command = "npm run build" # Build command, adjust if you have a different build process  # Directory for Netlify Functions (optional)
  publish = "dist"          # Directory to publish (adjust if needed)

[build.environment]
  NODE_VERSION = "20.18.1"     # Specify the Node.js version


[dev]
  command = "npm run start" # Command to start your app locally (adjust if needed)
# Directory for Netlify Functions (optional)

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

